### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by yoloVoe** [jpittis/rust-xds-grpc#1]
Hello Jake!
This is a really nice repo! In particular, I found the `xds/build.sh` script to be useful.
I would like to submit a PR, updating the emitted code & fixing/pinning the versions of the packages (like `protoc`) used (via a Dockerfile), as well as some other nits.

Would you be open to such a PR?

**Comment by jpittis** [comment]
Sorry for not responding for a billion years. I just updated this repo to xDS v3, switched the build script over to Rust, and pinned the git dependencies as submodules. Hopefully this code actually works... I hope to try to refresh https://github.com/jpittis/rust-control-plane based on these updates 🔜 ™️.

There's also https://github.com/bpowers/rust-envoy-control-plane as an alternative v3 implementation.

**Comment by jpittis** [comment]
Okay, I've started playing around with this for realz in https://github.com/jpittis/rust-control-plane.

Contributions are definitely welcome here, and probably there in a few weeks.
